### ISSUE TITLE
ue4-t2 - Test für Random Methode schreiben

### ISSUE THREAD

**Issue by denisr18** [i-pejic/fh-campus02-swe-2023#20]
Unit test darf mehr als eine Zufallszahl generieren (z.B. mit xem
Seed)
z.B. testen, ob sowohl Minimum als auch Maximum generiert
werden können
Zufallsfunktionalität in eigene Klasse auslagern kann das Unit-
Testing erleichtern

**Comment by DavidFriedl2407** [comment]
fine
